"""make student fields nullable

Revision ID: 9c3851f8ac6a
Revises: 390669fd25a0
Create Date: 2026-03-10 18:10:05.808554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c3851f8ac6a'
down_revision: Union[str, Sequence[str], None] = '390669fd25a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('companies', 'contact_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('coordinators', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('students', 'student_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('students', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('students', 'student_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('coordinators', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('companies', 'contact_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('companies', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
