"""cascade delete applications on job delete

Revision ID: caf2b033e02c
Revises: 51dfce0b26e6
Create Date: 2026-03-13 13:45:36.743922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caf2b033e02c'
down_revision: Union[str, Sequence[str], None] = '51dfce0b26e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE jobstatus ADD VALUE IF NOT EXISTS 'pending'")
    op.execute("ALTER TYPE jobstatus ADD VALUE IF NOT EXISTS 'approved'")
    op.execute("ALTER TYPE jobstatus ADD VALUE IF NOT EXISTS 'rejected'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('applications_job_id_fkey'), 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'job_postings', ['job_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('job_postings', 'rejection_note')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key(op.f('applications_job_id_fkey'), 'applications', 'job_postings', ['job_id'], ['id'])
    # ### end Alembic commands ###
